/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ndk_deerclops_com_ndksample_HelloNdk */

#ifndef _Included_ndk_deerclops_com_ndksample_HelloNdk
#define _Included_ndk_deerclops_com_ndksample_HelloNdk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ndk_deerclops_com_ndksample_HelloNdk
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ndk_deerclops_com_ndksample_HelloNdk_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
