/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ndk_deerclops_com_ndksample_HiNdk */

#ifndef _Included_ndk_deerclops_com_ndksample_HiNdk
#define _Included_ndk_deerclops_com_ndksample_HiNdk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ndk_deerclops_com_ndksample_HiNdk
 * Method:    getStrFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ndk_deerclops_com_ndksample_HiNdk_getStrFromC
  (JNIEnv *, jclass);

/*
 * Class:     ndk_deerclops_com_ndksample_HiNdk
 * Method:    transferFromStruct
 * Signature: ()Lndk/deerclops/com/ndksample/entity/SampleEntity;
 */
JNIEXPORT jobject JNICALL Java_ndk_deerclops_com_ndksample_HiNdk_transferFromStruct
  (JNIEnv *, jclass);

/*
 * Class:     ndk_deerclops_com_ndksample_HiNdk
 * Method:    getSampleArrayList
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_ndk_deerclops_com_ndksample_HiNdk_getSampleArrayList
  (JNIEnv *, jclass);

/*
 * Class:     ndk_deerclops_com_ndksample_HiNdk
 * Method:    printStruct
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ndk_deerclops_com_ndksample_HiNdk_printStruct
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
