/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ndk_deerclops_com_ndksample_HiNdk */

#ifndef _Included_ndk_deerclops_com_ndksample_HiNdk
#define _Included_ndk_deerclops_com_ndksample_HiNdk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ndk_deerclops_com_ndksample_HiNdk
 * Method:    getStrFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ndk_deerclops_com_ndksample_HiNdk_getStrFromC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
