/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ndk_deerclops_com_ndksample_EncryptHelper */

#ifndef _Included_ndk_deerclops_com_ndksample_EncryptHelper
#define _Included_ndk_deerclops_com_ndksample_EncryptHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ndk_deerclops_com_ndksample_EncryptHelper
 * Method:    encrypt
 * Signature: (Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ndk_deerclops_com_ndksample_EncryptHelper_encrypt
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     ndk_deerclops_com_ndksample_EncryptHelper
 * Method:    decrypt
 * Signature: (Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ndk_deerclops_com_ndksample_EncryptHelper_decrypt
  (JNIEnv *, jclass, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
